<a href="https://colab.research.google.com/github/RomanNihal/Machine_Learning/blob/main/working_with_CSV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import pandas

In [ ]:
import pandas as pd

# Read from a local file

In [ ]:
pd.read_csv("placement.csv")

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

# Read using url

In [ ]:
import requests
from io import StringIO
url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)
pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

# Tab separated file or .tsv

In [ ]:
pd.read_csv("sample-1.tsv", sep="\t")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,2022,Create more with themes Go to Format >> Theme
0,NaN,JANUARY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FEBRUARY,...,MARCH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,S,M,T,W,T,F,S,NaN,S,...,S,M,T,W,T,F,S,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,...,NaN,NaN,1,2,3,4,5,NaN,NaN,NaN
3,NaN,2,3,4,5,6,7,8,NaN,6,...,6,7,8,9,10,11,12,NaN,NaN,NaN
4,NaN,9,10,11,12,13,14,15,NaN,13,...,13,14,15,16,17,18,19,NaN,NaN,NaN
5,NaN,16,17,18,19,20,21,22,NaN,20,...,20,21,22,23,24,25,26,NaN,NaN,NaN
6,NaN,23,24,25,26,27,28,29,NaN,27,...,27,28,29,30,31,NaN,NaN,NaN,NaN,NaN
7,NaN,30,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,APRIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MAY,...,JUNE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,S,M,T,W,T,F,S,NaN,S,...,S,M,T,W,T,F,S,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,1,2,NaN,1,...,NaN,NaN,NaN,1,2,3,4,NaN,NaN,NaN
12,NaN,3,4,5,6,7,8,9,NaN,8,...,5,6,7,8,9,10,11,NaN,NaN,NaN
13,NaN,10,11,12,13,14,15,16,NaN,15,...,12,13,14,15,16,17,18,NaN,NaN,NaN
14,NaN,17,18,19,20,21,22,23,NaN,22,...,19,20,21,22,23,24,25,NaN,NaN,NaN
15,NaN,24,25,26,27,28,29,30,NaN,29,...,26,27,28,29,30,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,JULY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AUGUST,...,SEPTEMBER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,S,M,T,W,T,F,S,NaN,S,...,S,M,T,W,T,F,S,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,1,2,NaN,NaN,...,NaN,NaN,NaN,NaN,1,2,3,NaN,NaN,NaN
21,NaN,3,4,5,6,7,8,9,NaN,7,...,4,5,6,7,8,9,10,NaN,NaN,NaN
22,NaN,10,11,12,13,14,15,16,NaN,14,...,11,12,13,14,15,16,17,NaN,NaN,NaN
23,NaN,17,18,19,20,21,22,23,NaN,21,...,18,19,20,21,22,23,24,NaN,NaN,NaN
24,NaN,24,25,26,27,28,29,30,NaN,28,...,25,26,27,28,29,30,NaN,NaN,NaN,NaN
25,NaN,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,OCTOBER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NOVEMBER,...,DECEMBER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,S,M,T,W,T,F,S,NaN,S,...,S,M,T,W,T,F,S,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,...,NaN,NaN,NaN,NaN,1,2,3,NaN,NaN,NaN
30,NaN,2,3,4,5,6,7,8,NaN,6,...,4,5,6,7,8,9,10,NaN,NaN,NaN
31,NaN,9,10,11,12,13,14,15,NaN,13,...,11,12,13,14,15,16,17,NaN,NaN,NaN
32,NaN,16,17,18,19,20,21,22,NaN,20,...,18,19,20,21,22,23,24,NaN,NaN,NaN
33,NaN,23,24,25,26,27,28,29,NaN,27,...,25,26,27,28,29,30,31,NaN,NaN,NaN
34,NaN,30,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# To add column name

In [ ]:
pd.read_csv("placement.csv", names=["I", "C", "R", "P"])

        I     C      R          P
0     NaN  cgpa     iq  placement
1     0.0   6.8  123.0          1
2     1.0   5.9  106.0          0
3     2.0   5.3  121.0          0
4     3.0   7.4  132.0          1
..    ...   ...    ...        ...
96   95.0   4.3  200.0          0
97   96.0   4.4   42.0          0
98   97.0   6.7  182.0          1
99   98.0   6.3  103.0          1
100  99.0   6.2  113.0          1

[101 rows x 4 columns]

# To turn a column as index

In [ ]:
pd.read_csv("placement.csv", names=["I", "C", "R", "P"], index_col="I")

         C      R          P
I
NaN   cgpa     iq  placement
0.0    6.8  123.0          1
1.0    5.9  106.0          0
2.0    5.3  121.0          0
3.0    7.4  132.0          1
...    ...    ...        ...
95.0   4.3  200.0          0
96.0   4.4   42.0          0
97.0   6.7  182.0          1
98.0   6.3  103.0          1
99.0   6.2  113.0          1

[101 rows x 3 columns]

# Turn 1st column into header

In [ ]:
pd.read_csv("sample-1.tsv", sep="\t", header=1)

,Unnamed: 0,JANUARY,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,FEBRUARY,...,MARCH,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,NaN,S,M,T,W,T,F,S,NaN,S,...,S,M,T,W,T,F,S,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,...,NaN,NaN,1,2,3,4,5,NaN,NaN,NaN
2,NaN,2,3,4,5,6,7,8,NaN,6,...,6,7,8,9,10,11,12,NaN,NaN,NaN
3,NaN,9,10,11,12,13,14,15,NaN,13,...,13,14,15,16,17,18,19,NaN,NaN,NaN
4,NaN,16,17,18,19,20,21,22,NaN,20,...,20,21,22,23,24,25,26,NaN,NaN,NaN
5,NaN,23,24,25,26,27,28,29,NaN,27,...,27,28,29,30,31,NaN,NaN,NaN,NaN,NaN
6,NaN,30,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,APRIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MAY,...,JUNE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,S,M,T,W,T,F,S,NaN,S,...,S,M,T,W,T,F,S,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,1,2,NaN,1,...,NaN,NaN,NaN,1,2,3,4,NaN,NaN,NaN
11,NaN,3,4,5,6,7,8,9,NaN,8,...,5,6,7,8,9,10,11,NaN,NaN,NaN
12,NaN,10,11,12,13,14,15,16,NaN,15,...,12,13,14,15,16,17,18,NaN,NaN,NaN
13,NaN,17,18,19,20,21,22,23,NaN,22,...,19,20,21,22,23,24,25,NaN,NaN,NaN
14,NaN,24,25,26,27,28,29,30,NaN,29,...,26,27,28,29,30,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,JULY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AUGUST,...,SEPTEMBER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,S,M,T,W,T,F,S,NaN,S,...,S,M,T,W,T,F,S,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,1,2,NaN,NaN,...,NaN,NaN,NaN,NaN,1,2,3,NaN,NaN,NaN
20,NaN,3,4,5,6,7,8,9,NaN,7,...,4,5,6,7,8,9,10,NaN,NaN,NaN
21,NaN,10,11,12,13,14,15,16,NaN,14,...,11,12,13,14,15,16,17,NaN,NaN,NaN
22,NaN,17,18,19,20,21,22,23,NaN,21,...,18,19,20,21,22,23,24,NaN,NaN,NaN
23,NaN,24,25,26,27,28,29,30,NaN,28,...,25,26,27,28,29,30,NaN,NaN,NaN,NaN
24,NaN,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,OCTOBER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NOVEMBER,...,DECEMBER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,S,M,T,W,T,F,S,NaN,S,...,S,M,T,W,T,F,S,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,...,NaN,NaN,NaN,NaN,1,2,3,NaN,NaN,NaN
29,NaN,2,3,4,5,6,7,8,NaN,6,...,4,5,6,7,8,9,10,NaN,NaN,NaN
30,NaN,9,10,11,12,13,14,15,NaN,13,...,11,12,13,14,15,16,17,NaN,NaN,NaN
31,NaN,16,17,18,19,20,21,22,NaN,20,...,18,19,20,21,22,23,24,NaN,NaN,NaN
32,NaN,23,24,25,26,27,28,29,NaN,27,...,25,26,27,28,29,30,31,NaN,NaN,NaN
33,NaN,30,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Use specific columns

In [ ]:
pd.read_csv("placement.csv", usecols=["cgpa", "iq"])

    cgpa     iq
0    6.8  123.0
1    5.9  106.0
2    5.3  121.0
3    7.4  132.0
4    5.8  142.0
..   ...    ...
95   4.3  200.0
96   4.4   42.0
97   6.7  182.0
98   6.3  103.0
99   6.2  113.0

[100 rows x 2 columns]

# For single colums and squeeze to make it a series object not data frame

In [ ]:
pd.read_csv("placement.csv", usecols=["cgpa"], squeeze=True)

<ipython-input-33-a9614ec683a5>:1: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  pd.read_csv("placement.csv", usecols=["cgpa"], squeeze=True)

0     6.8
1     5.9
2     5.3
3     7.4
4     5.8
     ...
95    4.3
96    4.4
97    6.7
98    6.3
99    6.2
Name: cgpa, Length: 100, dtype: float64

# Skiprows/nrows Parameter
Line numbers to skip (0-indexed) or number of lines to skip (int) at the start of the file. If callable, the callable function will be evaluated against the row indices, returning True if the row should be skipped and False otherwise. An example Of a valid callable argument would be Lambda x: x in [0,2].

In [ ]:
pd.read_csv("placement.csv", skiprows=[1,4])

    Unnamed: 0  cgpa     iq  placement
0            1   5.9  106.0          0
1            2   5.3  121.0          0
2            4   5.8  142.0          0
3            5   7.1   48.0          1
4            6   5.7  143.0          0
..         ...   ...    ...        ...
93          95   4.3  200.0          0
94          96   4.4   42.0          0
95          97   6.7  182.0          1
96          98   6.3  103.0          1
97          99   6.2  113.0          1

[98 rows x 4 columns]

In [ ]:
pd.read_csv("placement.csv", nrows=10)

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0
5           5   7.1   48.0          1
6           6   5.7  143.0          0
7           7   5.0   63.0          0
8           8   6.1  156.0          0
9           9   5.1   66.0          0

# Encoding parameter not utf 8
UnicodeDecodeError

In [ ]:
pd.read_csv("zomato.csv", encoding="latin-1")

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

# Column different in different rows, bad lines

In [ ]:
pd.read_csv("zomato.csv", encoding="latin-1", error_bad_lines=False)

<ipython-input-7-f2bf536ed9d1>:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  pd.read_csv("zomato.csv", encoding="latin-1", error_bad_lines=False)

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

# Change Data type

In [ ]:
pd.read_csv("aug_train.csv", dtype={"target":int}).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  int64
dtypes: float64(1), int64(3), object(10)
memory usage: 2.0+ MB

# Date handling
default string so need to convert into date time formate

In [ ]:
pd.read_csv("IPL Matches 2008-2020.csv", parse_dates=["date"]).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    datetime64[ns]
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(13)
memory usage: 108.5+ KB

# Converters

In [ ]:
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    else:
        return name

In [ ]:
pd.read_csv("IPL Matches 2008-2020.csv",converters={"team1":rename})

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,RCB,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,RCB,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

# Change a columns value NaN

In [ ]:
pd.read_csv("aug_train.csv",na_values=["Male"])

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,NaN,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,NaN,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,NaN,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,NaN,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

# Loading a huge dataset in chunks
if the data set is to large then we can divide into chunks and then can access them using loop

In [ ]:
dfs = pd.read_csv('aug_train.csv',chunksize=5000)

In [ ]:
for chunks in dfs:
    print(chunks.shape)

(5000, 14)
(5000, 14)
(5000, 14)
(4158, 14)